# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "skip-bo" and “todo-database”
# The service “skip-bo” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image 
# from Docker Hub - https://hub.docker.com/_/mongo. 
# You can add other services your application may depend on here.

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    ports:
      - 5432
  

  skip-bo-client:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - skip-bo-socket
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/app/front-end
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

    
  skip-bo-socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    volumes:
      - ./socket:/app/socket
    ports:
      - 8040:8000
